language: python

python:
  - "2.7"
  - "3.6"

sudo: false

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

install:
  - pip install -r requirements.txt

before_script:
  - git submodule update --init --recursive

script:
  # Try to install the package
  - pip install .

  # Run tests
  - pytest -vv

notifications:
  email:
    on_failure: change

deploy:
  provider: pypi
  user: Tobias.Bieniek
  password:
    secure: a7VeLjfa5BqojsRNa+RLu8YaagM1FFEzfuovLYnUxd0EC+6060VZyXBp06wINpqntDYPl4qfdNjZcAWsoSh02apjWYCw9LiRkRB5FlygulTFyUbc/qW5Ol/NzkQP2jpMW82eehE7wroj9Dfwp0zU4WDgUugPmDQxtpHRSR+34mA=
  on:
    tags: true
    repo: Turbo87/py-xcsoar
